// Flat ESLint config (eslint v9). Base setup only; no project-local
// rule overrides yet (per WP-W2-01: "base config, no rule overrides").
// WP-W2-08 may layer in shadcn/Tailwind specifics.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default [
  {
    // `src/lib/bindings.ts` is regenerated by tauri-specta (cargo run
    // --bin export-bindings). The auto-emitter writes one
    // `error: e as any` line we can't avoid without forking the
    // generator; AGENTS.md forbids hand-editing the file. Ignoring
    // here keeps the WP-W2-03 lint gate green without weakening the
    // rule for the rest of the source tree.
    ignores: [
      "dist/**",
      "node_modules/**",
      ".vite/**",
      "coverage/**",
      "src/lib/bindings.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
      },
    },
  },
];
