//! Wire shapes exchanged with the Python sidecar.
//!
//! Inbound: `WireSpan` + the `SidecarEvent` envelope decoded from each
//! stdout frame. Outbound (to the frontend): `RunSpanPayload` plus the
//! `SerializableWireSpan` adapter that re-emits a `WireSpan` in the exact
//! camelCase shape `crate::models::Span` expects.

use serde::{Deserialize, Serialize};
use serde_json::Value;

// --------------------------------------------------------------------- //
// Inbound event shapes (from the Python sidecar)                         //
// --------------------------------------------------------------------- //

/// Wire-shape of one span as sent by the sidecar. Mirrors
/// `crate::models::Span`'s **camelCase** serialization with
/// `attrs_json` carried as a JSON string (TEXT column).
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct WireSpan {
    pub(super) id: String,
    pub(super) run_id: String,
    pub(super) parent_span_id: Option<String>,
    pub(super) name: String,
    #[serde(rename = "type")]
    pub(super) span_type: String,
    pub(super) t0_ms: i64,
    pub(super) duration_ms: Option<i64>,
    pub(super) attrs_json: String,
    pub(super) prompt: Option<String>,
    pub(super) response: Option<String>,
    pub(super) is_running: bool,
}

/// Top-level event envelope. Either a span event (`span.created` /
/// `.updated` / `.closed`) or a run completion. `event="ready"` /
/// `event="error"` are also accepted; the read loop logs them and
/// keeps going.
#[derive(Debug, Deserialize)]
#[serde(tag = "event", rename_all = "snake_case")]
#[serde(rename_all_fields = "camelCase")]
pub(super) enum SidecarEvent {
    /// `span.created` event — sidecar opened a new span.
    #[serde(rename = "span.created")]
    SpanCreated {
        run_id: String,
        span: WireSpan,
    },
    /// `span.updated` event — partial progress on an open span.
    /// Currently emitted by the workflow only on demand (Week 2 has
    /// none); the read loop tolerates it for forward-compat.
    #[serde(rename = "span.updated")]
    SpanUpdated {
        run_id: String,
        span: WireSpan,
    },
    /// `span.closed` event — span finalised with `is_running=false`
    /// and a `duration_ms`.
    #[serde(rename = "span.closed")]
    SpanClosed {
        run_id: String,
        span: WireSpan,
    },
    /// `run.completed` envelope — the sidecar is done with this run.
    /// `error` carries the optional error message.
    #[serde(rename = "run.completed")]
    RunCompleted {
        run_id: String,
        status: String,
        #[serde(default)]
        error: Option<String>,
    },
    /// `ready` — emitted once at sidecar startup. Useful for the UI
    /// "Starting agent" pill (WP-W2-04 §"Notes / risks").
    Ready,
    /// `error` — sidecar hit a non-fatal protocol error (bad frame,
    /// unknown method). Logged; the loop keeps reading.
    Error {
        #[serde(default)]
        message: Option<String>,
    },
}

// --------------------------------------------------------------------- //
// Outbound payload (to the frontend, via Tauri events)                   //
// --------------------------------------------------------------------- //

/// Discriminator we put on the `runs:{id}:span` Tauri event payload
/// so the frontend can switch on `kind` without inspecting the
/// `is_running` boolean. Per the orchestrator brief, `:` (not `.`) is
/// the canonical separator because Tauri 2.10 rejects `.` in event
/// names.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct RunSpanPayload<'a> {
    /// `"created" | "updated" | "closed"`.
    pub(super) kind: &'a str,
    pub(super) span: &'a Value,
}

/// Tiny adapter so we can re-serialize `WireSpan` into JSON without
/// rewriting all of its serde renames in a sister struct.
pub(super) struct SerializableWireSpan<'a>(pub(super) &'a WireSpan);

impl<'a> Serialize for SerializableWireSpan<'a> {
    fn serialize<S: serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {
        // The frontend's `Span` deserialiser (generated by tauri-specta
        // from `crate::models::Span`) expects the same camelCase shape
        // the sidecar emits, so a direct passthrough is sufficient.
        use serde::ser::SerializeStruct;
        let s = self.0;
        let mut st = ser.serialize_struct("Span", 12)?;
        st.serialize_field("id", &s.id)?;
        st.serialize_field("runId", &s.run_id)?;
        st.serialize_field("parentSpanId", &s.parent_span_id)?;
        st.serialize_field("name", &s.name)?;
        st.serialize_field("type", &s.span_type)?;
        st.serialize_field("t0Ms", &s.t0_ms)?;
        st.serialize_field("durationMs", &s.duration_ms)?;
        st.serialize_field("attrsJson", &s.attrs_json)?;
        st.serialize_field("prompt", &s.prompt)?;
        st.serialize_field("response", &s.response)?;
        st.serialize_field("isRunning", &s.is_running)?;
        // Indent is computed at read time by `runs:get`; events
        // never carry a meaningful depth, so emit 0 and let
        // `useRun` (WP-W2-08) recompute against the in-memory tree.
        st.serialize_field("indent", &0_i64)?;
        st.end()
    }
}
