// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	healthDb: () => typedError<DbHealth, string>(__TAURI_INVOKE("health_db")),
	agentsList: () => typedError<Agent[], AppErrorWire>(__TAURI_INVOKE("agents_list")),
	agentsGet: (id: string) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_get", { id })),
	agentsCreate: (input: AgentCreateInput) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_create", { input })),
	agentsUpdate: (id: string, patch: AgentPatch) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_update", { id, patch })),
	agentsDelete: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("agents_delete", { id })),
	workflowsList: () => typedError<Workflow[], AppErrorWire>(__TAURI_INVOKE("workflows_list")),
	workflowsGet: (id: string) => typedError<WorkflowDetail, AppErrorWire>(__TAURI_INVOKE("workflows_get", { id })),
	runsList: (filter: {
	status: string | null,
	workflowId: string | null,
} | null) => typedError<Run[], AppErrorWire>(__TAURI_INVOKE("runs_list", { filter })),
	runsGet: (id: string) => typedError<RunDetail, AppErrorWire>(__TAURI_INVOKE("runs_get", { id })),
	/**
	 *  Insert a `runs` row with `status='running'` and dispatch the run
	 *  to the LangGraph sidecar.
	 * 
	 *  The sidecar handle is looked up via `AppHandle::try_state` rather
	 *  than as a `tauri::State` argument because `Option<State<...>>` is
	 *  not a `specta::Type` and the binding generator rejects it. Tests
	 *  (and CI runners without a synced Python venv) skip the dispatch
	 *  path naturally — `try_state::<SidecarHandle>` returns `None` and
	 *  the inserted run row is the only side-effect.
	 */
	runsCreate: (workflowId: string) => typedError<Run, AppErrorWire>(__TAURI_INVOKE("runs_create", { workflowId })),
	runsCancel: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("runs_cancel", { id })),
	mcpList: () => typedError<Server[], AppErrorWire>(__TAURI_INVOKE("mcp_list")),
	mcpInstall: (id: string) => typedError<Server, AppErrorWire>(__TAURI_INVOKE("mcp_install", { id })),
	mcpUninstall: (id: string) => typedError<Server, AppErrorWire>(__TAURI_INVOKE("mcp_uninstall", { id })),
	/**
	 *  `mcp:listTools(serverId)` — return persisted tools for one server.
	 *  Empty list for uninstalled or unknown servers (the agent runtime
	 *  treats that as "no capabilities", which is the correct fallback).
	 */
	mcpListTools: (serverId: string) => typedError<Tool[], AppErrorWire>(__TAURI_INVOKE("mcp_list_tools", { serverId })),
	/**
	 *  `mcp:callTool(serverId, name, argsJson)` — execute one tool
	 *  against a freshly-spawned server. `argsJson` is the JSON-stringified
	 *  argument object; the server validates it against its `inputSchema`
	 *  and surfaces any schema violation as a structured `isError=true`
	 *  result.
	 * 
	 *  Why a string instead of a typed object: the tool's argument shape
	 *  is whatever the MCP server declares, which the Rust side has no
	 *  compile-time knowledge of. Passing JSON as a `String` keeps the
	 *  `bindings.ts` signature clean (`argsJson: string`) — the caller is
	 *  expected to do `JSON.stringify(args)` at the boundary, and the
	 *  frontend `useMcpCallTool` hook (Week 3) will hide that cermony.
	 */
	mcpCallTool: (serverId: string, name: string, argsJson: string) => typedError<CallToolResult, AppErrorWire>(__TAURI_INVOKE("mcp_call_tool", { serverId, name, argsJson })),
	terminalList: () => typedError<Pane[], AppErrorWire>(__TAURI_INVOKE("terminal_list")),
	/**
	 *  Fork a PTY, spawn the platform default shell (or `input.cmd` if
	 *  supplied), and return the freshly-inserted `Pane` row. The reader
	 *  and waiter tasks run on the tokio runtime; output streams via
	 *  `panes:{id}:line` Tauri events.
	 */
	terminalSpawn: (input: PaneSpawnInput) => typedError<Pane, AppErrorWire>(__TAURI_INVOKE("terminal_spawn", { input })),
	/**
	 *  Terminate the pane's child process. Idempotent — kill on an already-
	 *  closed pane updates `panes` row state without erroring (so the UI
	 *  can fire-and-forget on close). 404 if the pane id was never seen.
	 */
	terminalKill: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_kill", { id })),
	/**
	 *  Send `data` (raw bytes — typically keystrokes) to the pane's PTY
	 *  stdin. Bytes are written verbatim; the shell handles line editing
	 *  and echoing.
	 */
	terminalWrite: (paneId: string, data: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_write", { paneId, data })),
	/**
	 *  Resize the PTY (SIGWINCH on Unix, SetConsoleScreenBufferInfoEx on
	 *  Windows). Frontend callers must throttle to ≤10/sec per the
	 *  WP-W2-06 risk register; we apply the resize as-is.
	 */
	terminalResize: (paneId: string, cols: number, rows: number) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_resize", { paneId, cols, rows })),
	/**
	 *  Return the most recent scrollback for a pane. Live panes read from
	 *  the in-memory ring; closed panes read from `pane_lines` (persisted
	 *  at pane close). `sinceSeq` (exclusive) lets the UI hydrate
	 *  incrementally on mount.
	 */
	terminalLines: (paneId: string, sinceSeq: number | null) => typedError<PaneLine[], AppErrorWire>(__TAURI_INVOKE("terminal_lines", { paneId, sinceSeq })),
	mailboxList: (sinceTs: number | null) => typedError<MailboxEntry[], AppErrorWire>(__TAURI_INVOKE("mailbox_list", { sinceTs })),
	/**
	 *  Insert one row, return the inserted entry, **and** emit a
	 *  `mailbox.new` Tauri event with that entry as payload (ADR-0006).
	 */
	mailboxEmit: (entry: MailboxEntryInput) => typedError<MailboxEntry, AppErrorWire>(__TAURI_INVOKE("mailbox_emit", { entry })),
};

/* Types */
// One row of `agents`. Mirrors `data.js#agents[]` exactly.
export type Agent = {
	id: string,
	name: string,
	model: string,
	temp: number,
	role: string,
};

/**
 *  Input shape for `agents:create`. `id` is generated server-side
 *  (ULID), so the frontend supplies only the user-visible fields.
 */
export type AgentCreateInput = {
	name: string,
	model: string,
	temp: number,
	role: string,
};

/**
 *  Input shape for `agents:update`. Every field is optional — only the
 *  fields actually sent are written. `id` is the URL parameter, not a
 *  patch field.
 */
export type AgentPatch = {
	name: string | null,
	model: string | null,
	temp: number | null,
	role: string | null,
};

/**
 *  Helper struct used purely to anchor the `specta::Type` derive on
 *  the wire shape we hand-serialize above. Without this, `bindings.ts`
 *  would not see `AppError` at all and frontend `Result<T, AppError>`
 *  would degrade to `Result<T, unknown>`.
 */
export type AppErrorWire = {
	kind: string,
	message: string,
};

/**
 *  Wire shape for `mcp:callTool` returns. Keeps a flat `{content,
 *  isError}` object so the frontend can rely on a single deserializer
 *  regardless of which tool was called.
 */
export type CallToolResult = {
	content: ToolContent[],
	isError: boolean,
};

/**
 *  Health payload returned to the frontend. Field names use
 *  camelCase so the future TS bindings need no remapping.
 * 
 *  `specta::Type` was added in WP-W2-03 so the type lands in
 *  `bindings.ts` alongside the rest of the command surface.
 */
export type DbHealth = {
	/**
	 *  Number of user tables in the schema (excludes sqlx + sqlite
	 *  internal tables). Should be 11 after WP-W2-02 migration.
	 */
	tables: number,
	/**
	 *  Mirrors `PRAGMA foreign_keys` for the connection used to
	 *  answer this call. Must be `true` for the wiring to be sane.
	 */
	foreignKeysOn: boolean,
};

export type Edge = {
	id: string,
	workflowId: string,
	fromNode: string,
	toNode: string,
	/**
	 *  SQLite stores 0/1 INTEGER; sqlx decodes that to `bool`
	 *  natively (`sqlx_sqlite::types::bool`).
	 */
	active: boolean,
};

/**
 *  One row of `mailbox`. Per the WP-W2-03 smoke-test block, input and
 *  output use `fromPane`/`toPane` (not the terminal-data mock's
 *  `from`/`to` shorthand).
 */
export type MailboxEntry = {
	/**
	 *  Synthetic stable id. The schema does not have a column for this
	 *  because mailbox entries are append-only and indexed by ts; the
	 *  id is computed from `rowid` so the frontend can key React
	 *  lists deterministically.
	 */
	id: number,
	// Unix epoch seconds.
	ts: number,
	fromPane: string,
	toPane: string,
	// Cross-pane event type, e.g. `task:done`.
	type: string,
	summary: string,
};

/**
 *  Input shape for `mailbox:emit`. `ts` is filled server-side at
 *  insert time; the frontend just describes the message.
 */
export type MailboxEntryInput = {
	fromPane: string,
	toPane: string,
	type: string,
	summary: string,
};

export type Node = {
	id: string,
	workflowId: string,
	// Constrained at SQL level to `'llm'|'tool'|'logic'|'human'|'mcp'`.
	kind: string,
	x: number,
	y: number,
	title: string,
	meta: string,
	status: string,
};

/**
 *  One row of `panes`. Maps `agent_kind` to `agent` to match the
 *  terminal-data mock's `agent` key.
 */
export type Pane = {
	id: string,
	workspace: string,
	/**
	 *  Mock key: `agent`. The DB column is `agent_kind` because
	 *  `agent` is a reserved word in some SQL dialects and the
	 *  schema future-proofs the rename. The wire stays `agent`.
	 */
	agent: string,
	role: string | null,
	cwd: string,
	status: string,
	pid: number | null,
	startedAt: number,
	closedAt: number | null,
};

/**
 *  One line of pane scrollback as returned by `terminal:lines`. Mirrors
 *  the per-line entries in the in-memory ring buffer and the `pane_lines`
 *  table column set; `seq` is the monotonic per-pane sequence number,
 *  `k` matches the schema's CHECK list (`'sys'|'prompt'|'command'|...`),
 *  and `text` is the LF-terminated line text with CSI cursor-control
 *  stripped (raw bytes still flow through the live Tauri event for
 *  xterm.js rendering in WP-W2-08).
 */
export type PaneLine = {
	seq: number,
	k: string,
	text: string,
};

/**
 *  Input shape for `terminal:spawn`. Fields chosen to match what the
 *  WP-06 PTY supervisor needs; `cwd` is the only strictly-required
 *  field — `agentKind` is inferred from `cmd` when omitted, and
 *  `cmd`/`cols`/`rows` fall back to the platform default shell at
 *  `80x24`.
 * 
 *  WP-W2-06 added `cmd`/`cols`/`rows`. The legacy WP-03 callers
 *  supplied `agentKind` directly; the field is now optional and
 *  defaults to either the substring match against `cmd` (claude-code /
 *  codex / gemini) or `"shell"` when no inference is possible.
 */
export type PaneSpawnInput = {
	cwd: string,
	/**
	 *  Override the default platform shell. `None` = pick automatically
	 *  (`pwsh.exe`/`powershell.exe` on Windows, `$SHELL` elsewhere).
	 */
	cmd: string | null,
	// Initial PTY column count. `None` = 80.
	cols: number | null,
	// Initial PTY row count. `None` = 24.
	rows: number | null,
	/**
	 *  Optional explicit agent kind. `None` triggers substring inference
	 *  from `cmd` (`claude-code`/`codex`/`gemini`/`shell`).
	 */
	agentKind: string | null,
	role: string | null,
	workspace: string | null,
};

/**
 *  One row of `runs`. Field renames map the storage column names to
 *  the keys the frontend mock uses (`workflow`, `dur`, `cost`).
 */
export type Run = {
	id: string,
	// Denormalized workflow display name. Mock key: `workflow`.
	workflow: string,
	/**
	 *  Original workflow id (FK target). Carried so the inspector
	 *  can deep-link without an extra `runs:get` round-trip.
	 */
	workflowId: string,
	/**
	 *  Unix epoch seconds. Mock key in `data.js` is the formatted
	 *  relative-time string `started`; the wire format here is a
	 *  number to stay type-stable, and the frontend hook formats it
	 *  for display.
	 */
	startedAt: number,
	/**
	 *  Mock key: `dur` (milliseconds). `Option` because a still-
	 *  running run has no duration yet.
	 */
	dur: number | null,
	// Mock key: `tokens`.
	tokens: number,
	// Mock key: `cost`.
	cost: number,
	// `'running'|'success'|'error'` (CHECK-constrained at SQL).
	status: string,
};

export type RunDetail = {
	run: Run,
	spans: Span[],
};

/**
 *  Optional filter for `runs:list`. Currently scopes by status only;
 *  extended by WP-04 once real run execution lands.
 */
export type RunFilter = {
	status: string | null,
	workflowId: string | null,
};

export type Server = {
	id: string,
	name: string,
	by: string,
	// Mock key: `desc`.
	desc: string,
	installs: number,
	rating: number,
	featured: boolean,
	installed: boolean,
};

export type Span = {
	id: string,
	runId: string,
	parentSpanId: string | null,
	name: string,
	// `'llm'|'tool'|'logic'|'human'|'http'`.
	type: string,
	t0Ms: number,
	durationMs: number | null,
	attrsJson: string,
	prompt: string | null,
	response: string | null,
	isRunning: boolean,
};

/**
 *  One row of `server_tools`. Materialised by [`crate::mcp::registry`]
 *  during `mcp:install`; consumed by the agent runtime (WP-W2-04) and
 *  surfaced to the frontend via `mcp:listTools`.
 * 
 *  `input_schema_json` is stored as a TEXT column (raw JSON Schema)
 *  so the frontend can hand it directly to a JSON-Schema validator
 *  without re-encoding. The wire shape uses `inputSchemaJson` to make
 *  the schema-vs-string distinction explicit.
 */
export type Tool = {
	serverId: string,
	name: string,
	description: string,
	inputSchemaJson: string,
};

/**
 *  One block of a `tools/call` response. Mirrors the MCP spec's
 *  content array element. We expose `text` natively and pass any
 *  other shape through as `other` so the UI can render unknown blocks
 *  best-effort instead of failing the whole call.
 */
export type ToolContent = { type: "text"; text: string } | { type: "other" };

export type Workflow = {
	id: string,
	name: string,
	/**
	 *  Unix epoch seconds when the workflow was last saved. Mirrors
	 *  the WP-W2-02 column.
	 */
	savedAt: number,
};

/**
 *  Composite payload for `workflows:get` — the workflow itself plus
 *  its full node and edge list. Matches the WP signature
 *  `→ { workflow: Workflow; nodes: Node[]; edges: Edge[] }`.
 */
export type WorkflowDetail = {
	workflow: Workflow,
	nodes: Node[],
	edges: Edge[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

