// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	healthDb: () => typedError<DbHealth, AppErrorWire>(__TAURI_INVOKE("health_db")),
	agentsList: () => typedError<Agent[], AppErrorWire>(__TAURI_INVOKE("agents_list")),
	agentsGet: (id: string) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_get", { id })),
	agentsCreate: (input: AgentCreateInput) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_create", { input })),
	agentsUpdate: (id: string, patch: AgentPatch) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_update", { id, patch })),
	agentsDelete: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("agents_delete", { id })),
	workflowsList: () => typedError<Workflow[], AppErrorWire>(__TAURI_INVOKE("workflows_list")),
	workflowsGet: (id: string) => typedError<WorkflowDetail, AppErrorWire>(__TAURI_INVOKE("workflows_get", { id })),
	runsList: (filter: {
	status: string | null,
	workflowId: string | null,
} | null) => typedError<Run[], AppErrorWire>(__TAURI_INVOKE("runs_list", { filter })),
	runsGet: (id: string) => typedError<RunDetail, AppErrorWire>(__TAURI_INVOKE("runs_get", { id })),
	/**
	 *  Insert a `runs` row with `status='running'` and dispatch the run
	 *  to the LangGraph sidecar.
	 * 
	 *  The sidecar handle is looked up via `AppHandle::try_state` rather
	 *  than as a `tauri::State` argument because `Option<State<...>>` is
	 *  not a `specta::Type` and the binding generator rejects it. Tests
	 *  (and CI runners without a synced Python venv) skip the dispatch
	 *  path naturally — `try_state::<SidecarHandle>` returns `None` and
	 *  the inserted run row is the only side-effect.
	 */
	runsCreate: (workflowId: string) => typedError<Run, AppErrorWire>(__TAURI_INVOKE("runs_create", { workflowId })),
	runsCancel: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("runs_cancel", { id })),
	meGet: () => typedError<Me, AppErrorWire>(__TAURI_INVOKE("me_get")),
	mcpList: () => typedError<Server[], AppErrorWire>(__TAURI_INVOKE("mcp_list")),
	mcpInstall: (id: string) => typedError<Server, AppErrorWire>(__TAURI_INVOKE("mcp_install", { id })),
	mcpUninstall: (id: string) => typedError<Server, AppErrorWire>(__TAURI_INVOKE("mcp_uninstall", { id })),
	/**
	 *  `mcp:listTools(serverId)` — return persisted tools for one server.
	 *  Empty list for uninstalled or unknown servers (the agent runtime
	 *  treats that as "no capabilities", which is the correct fallback).
	 */
	mcpListTools: (serverId: string) => typedError<Tool[], AppErrorWire>(__TAURI_INVOKE("mcp_list_tools", { serverId })),
	/**
	 *  `mcp:callTool(serverId, name, argsJson)` — execute one tool
	 *  against a freshly-spawned server. `argsJson` is the JSON-stringified
	 *  argument object; the server validates it against its `inputSchema`
	 *  and surfaces any schema violation as a structured `isError=true`
	 *  result.
	 * 
	 *  Why a string instead of a typed object: the tool's argument shape
	 *  is whatever the MCP server declares, which the Rust side has no
	 *  compile-time knowledge of. Passing JSON as a `String` keeps the
	 *  `bindings.ts` signature clean (`argsJson: string`) — the caller is
	 *  expected to do `JSON.stringify(args)` at the boundary, and the
	 *  frontend `useMcpCallTool` hook (Week 3) will hide that cermony.
	 */
	mcpCallTool: (serverId: string, name: string, argsJson: string) => typedError<CallToolResult, AppErrorWire>(__TAURI_INVOKE("mcp_call_tool", { serverId, name, argsJson })),
	/**
	 *  Materialise every pane with mock-shape parity. The five derived
	 *  fields (`tokens_in/out/cost_usd/uptime/approval`) are filled here
	 *  rather than via `sqlx::FromRow` because `approval` carries a
	 *  JSON-on-disk blob: the SQL column is `last_approval_json TEXT`
	 *  (migration 0003), which is decoded into `ApprovalBanner` only when
	 *  the pane is currently `awaiting_approval`. Idle / running / closed
	 *  panes get `Pane.approval = None` even if a stale blob lingers in
	 *  the column from a previous awaiting cycle.
	 * 
	 *  `tokens_in/out/cost_usd/uptime` always project as SQL `NULL` — the
	 *  Charter Constraint #1 *display-derived carve-out* puts these in
	 *  the frontend hook (Week 3 will source `tokens_*` and `cost_usd`
	 *  from `runs_spans`; `uptime` stays display-derived).
	 */
	terminalList: () => typedError<Pane[], AppErrorWire>(__TAURI_INVOKE("terminal_list")),
	/**
	 *  Fork a PTY, spawn the platform default shell (or `input.cmd` if
	 *  supplied), and return the freshly-inserted `Pane` row. The reader
	 *  and waiter tasks run on the tokio runtime; output streams via
	 *  `panes:{id}:line` Tauri events.
	 */
	terminalSpawn: (input: PaneSpawnInput) => typedError<Pane, AppErrorWire>(__TAURI_INVOKE("terminal_spawn", { input })),
	/**
	 *  Terminate the pane's child process. Idempotent — kill on an already-
	 *  closed pane updates `panes` row state without erroring (so the UI
	 *  can fire-and-forget on close). 404 if the pane id was never seen.
	 */
	terminalKill: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_kill", { id })),
	/**
	 *  Send `data` (raw bytes — typically keystrokes) to the pane's PTY
	 *  stdin. Bytes are written verbatim; the shell handles line editing
	 *  and echoing.
	 */
	terminalWrite: (paneId: string, data: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_write", { paneId, data })),
	/**
	 *  Resize the PTY (SIGWINCH on Unix, SetConsoleScreenBufferInfoEx on
	 *  Windows). Frontend callers must throttle to ≤10/sec per the
	 *  WP-W2-06 risk register; we apply the resize as-is.
	 */
	terminalResize: (paneId: string, cols: number, rows: number) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_resize", { paneId, cols, rows })),
	/**
	 *  Return the most recent scrollback for a pane. Live panes read from
	 *  the in-memory ring; closed panes read from `pane_lines` (persisted
	 *  at pane close). `sinceSeq` (exclusive) lets the UI hydrate
	 *  incrementally on mount.
	 */
	terminalLines: (paneId: string, sinceSeq: number | null) => typedError<PaneLine[], AppErrorWire>(__TAURI_INVOKE("terminal_lines", { paneId, sinceSeq })),
	mailboxList: (sinceTs: number | null) => typedError<MailboxEntry[], AppErrorWire>(__TAURI_INVOKE("mailbox_list", { sinceTs })),
	/**
	 *  Insert one row, return the inserted entry, **and** emit a
	 *  `mailbox.new` Tauri event with that entry as payload (ADR-0006).
	 */
	mailboxEmit: (entry: MailboxEntryInput) => typedError<MailboxEntry, AppErrorWire>(__TAURI_INVOKE("mailbox_emit", { entry })),
	/**
	 *  Write a secret to the OS keychain. Empty `value` is rejected so
	 *  the keychain never holds a sentinel "" that `has_secret` would
	 *  then have to second-guess.
	 */
	secretsSet: (key: string, value: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("secrets_set", { key, value })),
	/**
	 *  Cheap presence probe. Honors the env-override path so
	 *  `NEURON_<KEY>=…` exported into a developer's shell counts as
	 *  "configured" without writing to the keychain first.
	 */
	secretsHas: (key: string) => typedError<boolean, AppErrorWire>(__TAURI_INVOKE("secrets_has", { key })),
	/**
	 *  Delete the keychain entry. Idempotent — a missing entry is not
	 *  an error so the frontend's "Forget API key" CTA can be wired
	 *  without a guard.
	 */
	secretsDelete: (key: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("secrets_delete", { key })),
	settingsGet: (key: string) => typedError<string | null, AppErrorWire>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("settings_set", { key, value })),
	settingsDelete: (key: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("settings_delete", { key })),
	/**
	 *  Return every setting as `(key, value)` pairs sorted by key.
	 *  Used by the W3-08 Settings route's "Advanced" panel; the
	 *  updated_at column is intentionally omitted from the wire shape
	 *  to keep the typegen surface trivial.
	 */
	settingsList: () => typedError<([string, string])[], AppErrorWire>(__TAURI_INVOKE("settings_list")),
	/**
	 *  Return every profile the registry knows about. Bundled defaults
	 *  always present (3 entries on a fresh install); workspace files
	 *  shadow bundled ones with the same `id`. Body and `source_path`
	 *  are stripped per `ProfileSummary`'s contract.
	 */
	swarmProfilesList: () => typedError<ProfileSummary[], AppErrorWire>(__TAURI_INVOKE("swarm_profiles_list")),
	/**
	 *  Spawn `claude` against the named profile, send `user_message`
	 *  once, return the parsed `result` event. Acceptance gate for
	 *  WP-W3-11 — proves the subprocess pipe is healthy end-to-end.
	 * 
	 *  60-second timeout absorbs Windows AV cold-start cost on first
	 *  spawn (per WP §"Notes / risks"). Subscription env is preserved
	 *  (no `ANTHROPIC_API_KEY` injected) per `binding::subscription_env`.
	 */
	swarmTestInvoke: (profileId: string, userMessage: string) => typedError<InvokeResult, AppErrorWire>(__TAURI_INVOKE("swarm_test_invoke", { profileId, userMessage })),
	/**
	 *  Drive a 3-stage swarm job to completion (WP-W3-12a §4).
	 * 
	 *  Walks `scout` → `planner` → `backend-builder` against the
	 *  substrate from W3-11, returning the aggregated `JobOutcome`. The
	 *  IPC blocks until the FSM finishes (Done / Failed). Two calls with
	 *  the same `workspace_id` serialize — the second returns
	 *  `AppError::WorkspaceBusy`. Two calls with different `workspace_id`s
	 *  run in parallel.
	 */
	swarmRunJob: (workspaceId: string, goal: string) => typedError<JobOutcome, AppErrorWire>(__TAURI_INVOKE("swarm_run_job", { workspaceId, goal })),
	/**
	 *  Signal cancellation for an in-flight swarm job (WP-W3-12c §4).
	 * 
	 *  Looks up `job_id` in the `JobRegistry`. Returns:
	 * 
	 *  - `Ok(())` if the job was in-flight and the cancel signal was
	 *    delivered. The FSM observes the signal at the next `select!`
	 *    point, emits `Cancelled` then `Finished`, and finalizes the
	 *    job as `Failed` with `last_error = "cancelled by user"`.
	 *  - `Err(AppError::NotFound)` if no job with the given id exists
	 *    in the registry.
	 *  - `Err(AppError::Conflict)` if the job is already terminal
	 *    (`Done`/`Failed`) — including a previous cancel that has
	 *    already finalized.
	 * 
	 *  Idempotency: a second cancel against the same in-flight job
	 *  either returns `Ok(())` (signal sent again, FSM ignores it
	 *  once finalized) or `Err(Conflict)` if the FSM has already
	 *  removed the cancel notify on its tail. The race is benign;
	 *  callers should treat both as "cancel acknowledged".
	 */
	swarmCancelJob: (jobId: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("swarm_cancel_job", { jobId })),
};

/* Types */
// One row of `agents`. Mirrors `data.js#agents[]` exactly.
export type Agent = {
	id: string,
	name: string,
	model: string,
	temp: number,
	role: string,
};

/**
 *  Input shape for `agents:create`. `id` is generated server-side
 *  (ULID), so the frontend supplies only the user-visible fields.
 */
export type AgentCreateInput = {
	name: string,
	model: string,
	temp: number,
	role: string,
};

/**
 *  Input shape for `agents:update`. Every field is optional — only the
 *  fields actually sent are written. `id` is the URL parameter, not a
 *  patch field.
 */
export type AgentPatch = {
	name: string | null,
	model: string | null,
	temp: number | null,
	role: string | null,
};

/**
 *  Helper struct used purely to anchor the `specta::Type` derive on
 *  the wire shape we hand-serialize above. Without this, `bindings.ts`
 *  would not see `AppError` at all and frontend `Result<T, AppError>`
 *  would degrade to `Result<T, unknown>`.
 */
export type AppErrorWire = {
	kind: string,
	message: string,
};

/**
 *  One approval banner blob. Populated by the terminal reader when
 *  an `awaiting_approval` regex matches; surfaced to the UI's amber
 *  banner strip per `NEURON_TERMINAL_REPORT.md`. Mock parity:
 *  `terminal-data.js#panes[0].approval` —
 *  `{tool, target, added, removed}`.
 */
export type ApprovalBanner = {
	tool: string,
	target: string,
	added: number,
	removed: number,
};

/**
 *  Wire shape for `mcp:callTool` returns. Keeps a flat `{content,
 *  isError}` object so the frontend can rely on a single deserializer
 *  regardless of which tool was called.
 */
export type CallToolResult = {
	content: ToolContent[],
	isError: boolean,
};

/**
 *  Health payload returned to the frontend. Field names use
 *  camelCase so the future TS bindings need no remapping.
 * 
 *  `specta::Type` was added in WP-W2-03 so the type lands in
 *  `bindings.ts` alongside the rest of the command surface.
 */
export type DbHealth = {
	/**
	 *  Number of user tables in the schema (excludes sqlx + sqlite
	 *  internal tables). Should be 11 after WP-W2-02 migration.
	 */
	tables: number,
	/**
	 *  Mirrors `PRAGMA foreign_keys` for the connection used to
	 *  answer this call. Must be `true` for the wiring to be sane.
	 */
	foreignKeysOn: boolean,
};

export type Edge = {
	id: string,
	workflowId: string,
	fromNode: string,
	toNode: string,
	/**
	 *  SQLite stores 0/1 INTEGER; sqlx decodes that to `bool`
	 *  natively (`sqlx_sqlite::types::bool`).
	 */
	active: boolean,
};

/**
 *  Output of one successful `SubprocessTransport::invoke`.
 * 
 *  `total_cost_usd` is what `claude` reports in the `result` event;
 *  `turn_count` reflects the number of model turns the child consumed
 *  before finishing (≤ `Profile.max_turns`).
 */
export type InvokeResult = {
	sessionId: string,
	assistantText: string,
	totalCostUsd: number,
	turnCount: number,
};

/**
 *  Final outcome returned by `swarm:run_job`. Mirrors `Job` minus
 *  the lifecycle bookkeeping fields the IPC caller doesn't need
 *  (no `state` mid-run, no `created_at_ms` since the wall-clock
 *  data is encoded in `total_duration_ms`).
 */
export type JobOutcome = {
	jobId: string,
	// Always `Done` or `Failed` — the FSM never returns mid-state.
	finalState: JobState,
	stages: StageResult[],
	// `Some` on `Failed`, `None` on `Done`.
	lastError: string | null,
	// Sum of `StageResult.total_cost_usd` across `stages`.
	totalCostUsd: number,
	// Sum of `StageResult.duration_ms` across `stages`.
	totalDurationMs: number,
};

/**
 *  Lifecycle states of a swarm job. Per WP §2:
 * 
 *  - `Init` — newly minted, before the first transition fires.
 *  - `Scout` / `Plan` / `Build` — the three happy-path stages.
 *  - `Review` / `Test` — reserved for W3-12d (reviewer +
 *    integration-tester profiles); FSM never enters them in 12a.
 *  - `Done` / `Failed` — terminal.
 * 
 *  `Hash` + `Eq` are derived so the FSM can build small lookup
 *  tables keyed on the state if it ever needs to (W3-12d).
 */
export type JobState = "init" | "scout" | "plan" | "build" | 
/**
 *  Reserved for W3-12d. FSM never enters this state in W3-12a;
 *  the next-state function asserts unreachable in debug builds.
 */
"review" | 
// Reserved for W3-12d. Same as `Review`.
"test" | "done" | 
/**
 *  Terminal failure state. Carries the last error in
 *  `Job.last_error`.
 */
"failed";

/**
 *  One row of `mailbox`. Wire keys `from`/`to` match the terminal-data
 *  mock per Charter Constraint #1; Rust fields keep the `_pane` suffix
 *  for SQL column binding and code clarity (see § "Mailbox wire keys"
 *  at the top of this module).
 */
export type MailboxEntry = {
	/**
	 *  Stable autoincrement id from migration 0002
	 *  (`INTEGER PRIMARY KEY AUTOINCREMENT`). Per ADR-0007 §3, mailbox
	 *  is the canonical autoincrement-int domain — opaque to
	 *  consumers, used solely as a React key. Monotonic, never reused
	 *  after `DELETE`.
	 */
	id: number,
	// Unix epoch seconds.
	ts: number,
	from: string,
	to: string,
	// Cross-pane event type, e.g. `task:done`.
	type: string,
	summary: string,
};

/**
 *  Input shape for `mailbox:emit`. `ts` is filled server-side at
 *  insert time; the frontend just describes the message. Wire keys
 *  `from`/`to` per Charter Constraint #1.
 */
export type MailboxEntryInput = {
	from: string,
	to: string,
	type: string,
	summary: string,
};

/**
 *  Composite shape returned by `me:get`. Combines `data.user` and
 *  `data.workspace` so the Sidebar mounts in one round-trip.
 */
export type Me = {
	user: User,
	workspace: Workspace,
};

export type Node = {
	id: string,
	workflowId: string,
	// Constrained at SQL level to `'llm'|'tool'|'logic'|'human'|'mcp'`.
	kind: string,
	x: number,
	y: number,
	title: string,
	meta: string,
	status: string,
};

/**
 *  One row of `panes`. Maps `agent_kind` to `agent` to match the
 *  terminal-data mock's `agent` key.
 * 
 *  The trailing five fields (`tokens_in`/`tokens_out`/`cost_usd`/
 *  `uptime`/`approval`) exist for mock-shape parity per Charter
 *  Constraint #1; their wire values are sourced as follows:
 * 
 *  - `tokens_in`/`tokens_out`/`cost_usd` — Week 2 always ship `None`;
 *    Week 3 will aggregate them from `runs_spans`.
 *  - `uptime` — backend always ships `None` per Charter #1
 *    *display-derived carve-out* (the frontend hook computes the
 *    `"12m 04s"` string from `started_at`).
 *  - `approval` — populated by `commands::terminal::terminal_list`
 *    from `panes.last_approval_json` *only* when `status =
 *    'awaiting_approval'`. The reader writes the JSON blob in
 *    `sidecar::terminal` on every regex match; the column is
 *    intentionally NOT cleared when the pane re-enters `running`,
 *    so a future debug view can replay the last seen banner.
 */
export type Pane = {
	id: string,
	workspace: string,
	/**
	 *  Mock key: `agent`. The DB column is `agent_kind` because
	 *  `agent` is a reserved word in some SQL dialects and the
	 *  schema future-proofs the rename. The wire stays `agent`.
	 */
	agent: string,
	role: string | null,
	cwd: string,
	status: string,
	pid: number | null,
	startedAt: number,
	closedAt: number | null,
	/**
	 *  Aggregate input tokens consumed by this pane's agent runtime.
	 *  Week 2: always `None` — populated in Week 3 from `runs_spans`.
	 */
	tokensIn: number | null,
	// Aggregate output tokens. Week 2: always `None`.
	tokensOut: number | null,
	// Aggregate USD cost. Week 2: always `None`.
	costUsd: number | null,
	/**
	 *  Display-derived `"12m 04s"` string. Per Charter Constraint #1
	 *  carve-out: backend ships `None`; the frontend hook computes
	 *  from `started_at`. Field exists for mock-shape parity only.
	 */
	uptime: string | null,
	/**
	 *  Approval banner blob extracted from the most recent
	 *  `awaiting_approval` regex match. `None` when the pane is not
	 *  currently awaiting approval; the underlying DB column may
	 *  still hold a stale blob from a previous awaiting cycle so the
	 *  reader path is resilient to noisy retries.
	 * 
	 *  `#[sqlx(skip)]`: `ApprovalBanner` is JSON-on-disk and does not
	 *  implement `sqlx::Decode`. `terminal_list` reads the raw
	 *  `last_approval_json` TEXT column via a manual row mapping and
	 *  hydrates this field after-the-fact; everywhere else (e.g.
	 *  `terminal_spawn` `RETURNING`) defaults to `None`.
	 */
	approval: ApprovalBanner | null,
};

/**
 *  One line of pane scrollback as returned by `terminal:lines`. Mirrors
 *  the per-line entries in the in-memory ring buffer and the `pane_lines`
 *  table column set; `seq` is the monotonic per-pane sequence number,
 *  `k` matches the schema's CHECK list (`'sys'|'prompt'|'command'|...`),
 *  and `text` is the LF-terminated line text with CSI cursor-control
 *  stripped (raw bytes still flow through the live Tauri event for
 *  xterm.js rendering in WP-W2-08).
 */
export type PaneLine = {
	seq: number,
	k: string,
	text: string,
};

/**
 *  Input shape for `terminal:spawn`. Fields chosen to match what the
 *  WP-06 PTY supervisor needs; `cwd` is the only strictly-required
 *  field — `agentKind` is inferred from `cmd` when omitted, and
 *  `cmd`/`cols`/`rows` fall back to the platform default shell at
 *  `80x24`.
 * 
 *  WP-W2-06 added `cmd`/`cols`/`rows`. The legacy WP-03 callers
 *  supplied `agentKind` directly; the field is now optional and
 *  defaults to either the substring match against `cmd` (claude-code /
 *  codex / gemini) or `"shell"` when no inference is possible.
 */
export type PaneSpawnInput = {
	cwd: string,
	/**
	 *  Override the default platform shell. `None` = pick automatically
	 *  (`pwsh.exe`/`powershell.exe` on Windows, `$SHELL` elsewhere).
	 */
	cmd: string | null,
	// Initial PTY column count. `None` = 80.
	cols: number | null,
	// Initial PTY row count. `None` = 24.
	rows: number | null,
	/**
	 *  Optional explicit agent kind. `None` triggers substring inference
	 *  from `cmd` (`claude-code`/`codex`/`gemini`/`shell`).
	 */
	agentKind: string | null,
	role: string | null,
	workspace: string | null,
};

/**
 *  Permission posture handed to the spawned `claude` subprocess.
 * 
 *  Phase 1 (this WP) treats the value as a binary gate inside
 *  `binding::build_specialist_args`:
 * 
 *  - `Plan` → `--permission-mode plan` (no `--dangerously-skip-permissions`).
 *  - everything else → `--dangerously-skip-permissions` (so the
 *    smoke command can run without a UI prompt).
 * 
 *  W3-12 introduces a per-tool allow / deny mapping; until then the
 *  richer `AcceptEdits` / `AcceptAll` distinction is metadata only.
 */
export type PermissionMode = 
// Read-only / planning posture — `--permission-mode plan`.
"plan" | 
// Auto-accept Edit / Write tool calls.
"acceptEdits" | 
/**
 *  Auto-accept everything including Bash. Phase 1 gate is the same
 *  as `AcceptEdits`; W3-12 splits the two.
 */
"acceptAll";

/**
 *  IPC-friendly subset of `crate::swarm::profile::Profile` returned by
 *  `swarm:profiles_list`. Strips the persona `body` (potentially
 *  kilobyte-class markdown) and the on-disk `source_path` so the
 *  frontend listing surface is cheap to fetch and stays free of
 *  host-filesystem leaks. The `source` discriminant lets the UI label
 *  each row as bundled-default vs. user-edited workspace override.
 * 
 *  The full `Profile` (incl. body) is loaded server-side on every
 *  `swarm:test_invoke`; the list command is purely a directory.
 */
export type ProfileSummary = {
	id: string,
	version: string,
	role: string,
	description: string,
	permissionMode: PermissionMode,
	maxTurns: number,
	allowedTools: string[],
	/**
	 *  `"bundled"` for profiles embedded via `include_dir!`,
	 *  `"workspace"` for files dropped under
	 *  `<app_data_dir>/agents/`.
	 */
	source: string,
};

/**
 *  One row of `runs`. Field renames map the storage column names to
 *  the keys the frontend mock uses (`workflow`, `dur`, `cost`).
 */
export type Run = {
	id: string,
	// Denormalized workflow display name. Mock key: `workflow`.
	workflow: string,
	/**
	 *  Original workflow id (FK target). Carried so the inspector
	 *  can deep-link without an extra `runs:get` round-trip.
	 */
	workflowId: string,
	/**
	 *  Unix epoch seconds. Mock key in `data.js` is the formatted
	 *  relative-time string `started`; the wire format here is a
	 *  number to stay type-stable, and the frontend hook formats it
	 *  for display.
	 */
	startedAt: number,
	/**
	 *  Mock key: `dur` (milliseconds). `Option` because a still-
	 *  running run has no duration yet.
	 */
	dur: number | null,
	// Mock key: `tokens`.
	tokens: number,
	// Mock key: `cost`.
	cost: number,
	// `'running'|'success'|'error'` (CHECK-constrained at SQL).
	status: string,
};

export type RunDetail = {
	run: Run,
	spans: Span[],
};

/**
 *  Optional filter for `runs:list`. Currently scopes by status only;
 *  extended by WP-04 once real run execution lands.
 */
export type RunFilter = {
	status: string | null,
	workflowId: string | null,
};

export type Server = {
	id: string,
	name: string,
	by: string,
	// Mock key: `desc`.
	desc: string,
	installs: number,
	rating: number,
	featured: boolean,
	installed: boolean,
};

export type Span = {
	id: string,
	runId: string,
	parentSpanId: string | null,
	name: string,
	// `'llm'|'tool'|'logic'|'human'|'http'`.
	type: string,
	t0Ms: number,
	durationMs: number | null,
	attrsJson: string,
	prompt: string | null,
	response: string | null,
	isRunning: boolean,
	/**
	 *  Tree depth derived from `parent_span_id` at read time via the
	 *  recursive CTE in `runs:get`. Not stored. `#[sqlx(default)]`
	 *  guards against ad-hoc SELECTs that omit the computed column;
	 *  no `serde(default)` because `Span` is never deserialised from
	 *  JSON (events use `WireSpan`), and we want the TypeScript field
	 *  to stay required for frontend consumers.
	 */
	indent: number,
};

/**
 *  Output of one completed FSM stage. Append-only — the FSM pushes
 *  one entry per stage that produced a result (success path) and
 *  stops on the first failure (which still records the failed
 *  stage's name in `Job.last_error` but does NOT push a `StageResult`
 *  for the failed stage in W3-12a — see `CoordinatorFsm::run_job`).
 */
export type StageResult = {
	/**
	 *  Which lifecycle stage produced this result. One of
	 *  `Scout` / `Plan` / `Build` in 12a.
	 */
	state: JobState,
	/**
	 *  `Profile.id` of the specialist that ran the stage —
	 *  `"scout"` / `"planner"` / `"backend-builder"`.
	 */
	specialistId: string,
	/**
	 *  The specialist's final assistant text (the `result` event's
	 *  `result` field; running deltas already concatenated).
	 */
	assistantText: string,
	/**
	 *  Subprocess session id (`system.init` event). Useful for
	 *  W3-12b's chat-history persistence.
	 */
	sessionId: string,
	/**
	 *  Cost reported by the `claude` `result.success` event. Sums
	 *  into `JobOutcome.total_cost_usd`.
	 */
	totalCostUsd: number,
	/**
	 *  Wall-clock duration of this stage's invoke, measured around
	 *  the `transport.invoke` await. Sums into
	 *  `JobOutcome.total_duration_ms`.
	 */
	durationMs: number,
};

/**
 *  Per-job lifecycle event streamed to `swarm:job:{job_id}:event`.
 * 
 *  One event name carries every transition in the FSM via a
 *  `kind` tag (matches W3-06's `runs:{id}:span` pattern). Frontend
 *  subscribers register one listener per job and switch on `kind`.
 * 
 *  Order on the happy path:
 * 
 *    `started → stage_started(scout) → stage_completed(scout)
 *            → stage_started(plan)  → stage_completed(plan)
 *            → stage_started(build) → stage_completed(build)
 *            → finished`
 * 
 *  On a stage error: `stage_started(stage) → finished` (no
 *  `stage_completed` for the failing stage).
 * 
 *  On cancellation: `… → stage_started(stage) → cancelled → finished`.
 */
export type SwarmJobEvent = 
/**
 *  Fires once at FSM start, after the workspace lock is
 *  acquired and the cancel notify is registered, before any
 *  stage spawns.
 */
{ kind: "started"; job_id: string; workspace_id: string; goal: string; created_at_ms: number } | 
/**
 *  Fires before every stage's `transport.invoke` is awaited.
 *  `state` is the upcoming lifecycle stage (Scout / Plan /
 *  Build); `prompt_preview` is the first 200 *chars* of the
 *  rendered prompt (char-bounded so multi-byte Turkish text
 *  is never split mid-codepoint).
 */
{ kind: "stage_started"; job_id: string; state: JobState; specialist_id: string; prompt_preview: string } | 
/**
 *  Fires after a stage's `StageResult` is built and pushed to
 *  the registry, on the success path only.
 */
{ kind: "stage_completed"; job_id: string; stage: StageResult } | 
/**
 *  Fires once at the FSM tail, regardless of outcome
 *  (Done / Failed / Cancelled). `outcome.final_state` is one
 *  of `Done` or `Failed`; cancelled jobs ride the `Failed`
 *  path with `last_error = Some("cancelled by user")`.
 */
{ kind: "finished"; job_id: string; outcome: JobOutcome } | 
/**
 *  Fires when the FSM observes the cancel `Notify` mid-stage,
 *  before the job is finalized as `Failed`. The next event on
 *  this channel is always `Finished`.
 */
{ kind: "cancelled"; job_id: string; cancelled_during: JobState };

/**
 *  One row of `server_tools`. Materialised by [`crate::mcp::registry`]
 *  during `mcp:install`; consumed by the agent runtime (WP-W2-04) and
 *  surfaced to the frontend via `mcp:listTools`.
 * 
 *  `input_schema_json` is stored as a TEXT column (raw JSON Schema)
 *  so the frontend can hand it directly to a JSON-Schema validator
 *  without re-encoding. The wire shape uses `inputSchemaJson` to make
 *  the schema-vs-string distinction explicit.
 */
export type Tool = {
	serverId: string,
	name: string,
	description: string,
	inputSchemaJson: string,
};

/**
 *  One block of a `tools/call` response. Mirrors the MCP spec's
 *  content array element. We expose `text` natively and pass any
 *  other shape through as `other` so the UI can render unknown blocks
 *  best-effort instead of failing the whole call.
 */
export type ToolContent = { type: "text"; text: string } | { type: "other" };

/**
 *  User profile fields surfaced in the Sidebar avatar / settings.
 *  Mock parity: `Neuron Design/app/data.js#user`.
 *  Week 2 hardcoded; Week 3 sources from a settings table.
 */
export type User = {
	initials: string,
	name: string,
};

export type Workflow = {
	id: string,
	name: string,
	/**
	 *  Unix epoch seconds when the workflow was last saved. Mirrors
	 *  the WP-W2-02 column.
	 */
	savedAt: number,
};

/**
 *  Composite payload for `workflows:get` — the workflow itself plus
 *  its full node and edge list. Matches the WP signature
 *  `→ { workflow: Workflow; nodes: Node[]; edges: Edge[] }`.
 */
export type WorkflowDetail = {
	workflow: Workflow,
	nodes: Node[],
	edges: Edge[],
};

/**
 *  Active workspace metadata. `count` is the number of workflows
 *  currently saved (denormalised from `SELECT COUNT(*) FROM workflows`).
 *  Mock parity: `Neuron Design/app/data.js#workspace`.
 */
export type Workspace = {
	name: string,
	count: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

