// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	healthDb: () => typedError<DbHealth, string>(__TAURI_INVOKE("health_db")),
	agentsList: () => typedError<Agent[], AppErrorWire>(__TAURI_INVOKE("agents_list")),
	agentsGet: (id: string) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_get", { id })),
	agentsCreate: (input: AgentCreateInput) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_create", { input })),
	agentsUpdate: (id: string, patch: AgentPatch) => typedError<Agent, AppErrorWire>(__TAURI_INVOKE("agents_update", { id, patch })),
	agentsDelete: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("agents_delete", { id })),
	workflowsList: () => typedError<Workflow[], AppErrorWire>(__TAURI_INVOKE("workflows_list")),
	workflowsGet: (id: string) => typedError<WorkflowDetail, AppErrorWire>(__TAURI_INVOKE("workflows_get", { id })),
	runsList: (filter: {
	status: string | null,
	workflowId: string | null,
} | null) => typedError<Run[], AppErrorWire>(__TAURI_INVOKE("runs_list", { filter })),
	runsGet: (id: string) => typedError<RunDetail, AppErrorWire>(__TAURI_INVOKE("runs_get", { id })),
	/**
	 *  **STUB.** Inserts a row in `runs` with `status='running'` and no
	 *  spans, returns the inserted row. Real execution lands in WP-04.
	 */
	runsCreate: (workflowId: string) => typedError<Run, AppErrorWire>(__TAURI_INVOKE("runs_create", { workflowId })),
	runsCancel: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("runs_cancel", { id })),
	mcpList: () => typedError<Server[], AppErrorWire>(__TAURI_INVOKE("mcp_list")),
	mcpInstall: (id: string) => typedError<Server, AppErrorWire>(__TAURI_INVOKE("mcp_install", { id })),
	mcpUninstall: (id: string) => typedError<Server, AppErrorWire>(__TAURI_INVOKE("mcp_uninstall", { id })),
	terminalList: () => typedError<Pane[], AppErrorWire>(__TAURI_INVOKE("terminal_list")),
	/**
	 *  **STUB.** Inserts a row in `panes` with `status='idle'` and no PTY.
	 *  Real PTY supervision lands in WP-06.
	 */
	terminalSpawn: (input: PaneSpawnInput) => typedError<Pane, AppErrorWire>(__TAURI_INVOKE("terminal_spawn", { input })),
	terminalKill: (id: string) => typedError<null, AppErrorWire>(__TAURI_INVOKE("terminal_kill", { id })),
	mailboxList: (sinceTs: number | null) => typedError<MailboxEntry[], AppErrorWire>(__TAURI_INVOKE("mailbox_list", { sinceTs })),
	/**
	 *  Insert one row, return the inserted entry, **and** emit a
	 *  `mailbox.new` Tauri event with that entry as payload (ADR-0006).
	 */
	mailboxEmit: (entry: MailboxEntryInput) => typedError<MailboxEntry, AppErrorWire>(__TAURI_INVOKE("mailbox_emit", { entry })),
};

/* Types */
// One row of `agents`. Mirrors `data.js#agents[]` exactly.
export type Agent = {
	id: string,
	name: string,
	model: string,
	temp: number,
	role: string,
};

/**
 *  Input shape for `agents:create`. `id` is generated server-side
 *  (ULID), so the frontend supplies only the user-visible fields.
 */
export type AgentCreateInput = {
	name: string,
	model: string,
	temp: number,
	role: string,
};

/**
 *  Input shape for `agents:update`. Every field is optional — only the
 *  fields actually sent are written. `id` is the URL parameter, not a
 *  patch field.
 */
export type AgentPatch = {
	name: string | null,
	model: string | null,
	temp: number | null,
	role: string | null,
};

/**
 *  Helper struct used purely to anchor the `specta::Type` derive on
 *  the wire shape we hand-serialize above. Without this, `bindings.ts`
 *  would not see `AppError` at all and frontend `Result<T, AppError>`
 *  would degrade to `Result<T, unknown>`.
 */
export type AppErrorWire = {
	kind: string,
	message: string,
};

/**
 *  Health payload returned to the frontend. Field names use
 *  camelCase so the future TS bindings need no remapping.
 * 
 *  `specta::Type` was added in WP-W2-03 so the type lands in
 *  `bindings.ts` alongside the rest of the command surface.
 */
export type DbHealth = {
	/**
	 *  Number of user tables in the schema (excludes sqlx + sqlite
	 *  internal tables). Should be 11 after WP-W2-02 migration.
	 */
	tables: number,
	/**
	 *  Mirrors `PRAGMA foreign_keys` for the connection used to
	 *  answer this call. Must be `true` for the wiring to be sane.
	 */
	foreignKeysOn: boolean,
};

export type Edge = {
	id: string,
	workflowId: string,
	fromNode: string,
	toNode: string,
	/**
	 *  SQLite stores 0/1 INTEGER; sqlx decodes that to `bool`
	 *  natively (`sqlx_sqlite::types::bool`).
	 */
	active: boolean,
};

/**
 *  One row of `mailbox`. Per the WP-W2-03 smoke-test block, input and
 *  output use `fromPane`/`toPane` (not the terminal-data mock's
 *  `from`/`to` shorthand).
 */
export type MailboxEntry = {
	/**
	 *  Synthetic stable id. The schema does not have a column for this
	 *  because mailbox entries are append-only and indexed by ts; the
	 *  id is computed from `rowid` so the frontend can key React
	 *  lists deterministically.
	 */
	id: number,
	// Unix epoch seconds.
	ts: number,
	fromPane: string,
	toPane: string,
	// Cross-pane event type, e.g. `task:done`.
	type: string,
	summary: string,
};

/**
 *  Input shape for `mailbox:emit`. `ts` is filled server-side at
 *  insert time; the frontend just describes the message.
 */
export type MailboxEntryInput = {
	fromPane: string,
	toPane: string,
	type: string,
	summary: string,
};

export type Node = {
	id: string,
	workflowId: string,
	// Constrained at SQL level to `'llm'|'tool'|'logic'|'human'|'mcp'`.
	kind: string,
	x: number,
	y: number,
	title: string,
	meta: string,
	status: string,
};

/**
 *  One row of `panes`. Maps `agent_kind` to `agent` to match the
 *  terminal-data mock's `agent` key.
 */
export type Pane = {
	id: string,
	workspace: string,
	/**
	 *  Mock key: `agent`. The DB column is `agent_kind` because
	 *  `agent` is a reserved word in some SQL dialects and the
	 *  schema future-proofs the rename. The wire stays `agent`.
	 */
	agent: string,
	role: string | null,
	cwd: string,
	status: string,
	pid: number | null,
	startedAt: number,
	closedAt: number | null,
};

/**
 *  Input shape for `terminal:spawn`. Fields chosen to match what the
 *  WP-06 PTY supervisor will need; only `agentKind` and `cwd` are
 *  strictly required for the WP-03 stub.
 */
export type PaneSpawnInput = {
	agentKind: string,
	cwd: string,
	role: string | null,
	workspace: string | null,
};

/**
 *  One row of `runs`. Field renames map the storage column names to
 *  the keys the frontend mock uses (`workflow`, `dur`, `cost`).
 */
export type Run = {
	id: string,
	// Denormalized workflow display name. Mock key: `workflow`.
	workflow: string,
	/**
	 *  Original workflow id (FK target). Carried so the inspector
	 *  can deep-link without an extra `runs:get` round-trip.
	 */
	workflowId: string,
	/**
	 *  Unix epoch seconds. Mock key in `data.js` is the formatted
	 *  relative-time string `started`; the wire format here is a
	 *  number to stay type-stable, and the frontend hook formats it
	 *  for display.
	 */
	startedAt: number,
	/**
	 *  Mock key: `dur` (milliseconds). `Option` because a still-
	 *  running run has no duration yet.
	 */
	dur: number | null,
	// Mock key: `tokens`.
	tokens: number,
	// Mock key: `cost`.
	cost: number,
	// `'running'|'success'|'error'` (CHECK-constrained at SQL).
	status: string,
};

export type RunDetail = {
	run: Run,
	spans: Span[],
};

/**
 *  Optional filter for `runs:list`. Currently scopes by status only;
 *  extended by WP-04 once real run execution lands.
 */
export type RunFilter = {
	status: string | null,
	workflowId: string | null,
};

export type Server = {
	id: string,
	name: string,
	by: string,
	// Mock key: `desc`.
	desc: string,
	installs: number,
	rating: number,
	featured: boolean,
	installed: boolean,
};

export type Span = {
	id: string,
	runId: string,
	parentSpanId: string | null,
	name: string,
	// `'llm'|'tool'|'logic'|'human'|'http'`.
	type: string,
	t0Ms: number,
	durationMs: number | null,
	attrsJson: string,
	prompt: string | null,
	response: string | null,
	isRunning: boolean,
};

export type Workflow = {
	id: string,
	name: string,
	/**
	 *  Unix epoch seconds when the workflow was last saved. Mirrors
	 *  the WP-W2-02 column.
	 */
	savedAt: number,
};

/**
 *  Composite payload for `workflows:get` — the workflow itself plus
 *  its full node and edge list. Matches the WP signature
 *  `→ { workflow: Workflow; nodes: Node[]; edges: Edge[] }`.
 */
export type WorkflowDetail = {
	workflow: Workflow,
	nodes: Node[],
	edges: Edge[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

